-- AlterTable
ALTER TABLE "Alert" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Bookmark" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ScraperLog" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Tender" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
