import { PrismaClient, TenderCategory, SourcePortal, TenderStatus } from "@prisma/client";

const prisma = new PrismaClient();

const tenders = [
  // ── Maharashtra ──────────────────────────────────────────────────────────
  {
    title: "Construction of 4-Lane Highway NH-48 from Pune to Nashik (Package 3)",
    referenceNumber: "PWD/MH/NH48/2025-26/PKG3",
    description:
      "Construction of 4-lane highway including bridges, culverts, underpasses, and service roads covering 42 km stretch of NH-48 in Maharashtra. Includes drainage, signage, and bituminous surfacing.",
    issuingAuthority: "Maharashtra Public Works Department",
    department: "National Highways Division, PWD Maharashtra",
    category: TenderCategory.CONSTRUCTION,
    state: "Maharashtra",
    district: "Pune",
    city: "Pune",
    estimatedValue: 48500000000,
    emdAmount: 97000000,
    publishedDate: new Date("2025-12-01"),
    submissionDeadline: new Date("2026-01-15"),
    prebidMeetingDate: new Date("2025-12-20"),
    tenderDocUrl: "https://mahatenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=5789",
    sourceUrl: "https://mahatenders.gov.in/nicgep/app?page=FrontEndTendersByOrganisation&service=page",
    sourcePortal: SourcePortal.MAHATENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-02T06:00:00"),
  },
  {
    title: "Supply, Installation & Commissioning of Data Centre Infrastructure for Mantralaya",
    referenceNumber: "DIT/MH/DC/2025-26/001",
    description:
      "Procurement and installation of hyperconverged infrastructure, storage, networking equipment, and physical security systems for the State Data Centre at Mantralaya, Mumbai. Includes 5-year AMC.",
    issuingAuthority: "Maharashtra IT Department",
    department: "Directorate of Information Technology, Maharashtra",
    category: TenderCategory.IT_SERVICES,
    state: "Maharashtra",
    district: "Mumbai",
    city: "Mumbai",
    estimatedValue: 620000000,
    emdAmount: 6200000,
    publishedDate: new Date("2025-11-15"),
    submissionDeadline: new Date("2025-12-30"),
    prebidMeetingDate: new Date("2025-11-28"),
    tenderDocUrl: "https://mahatenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=5612",
    sourceUrl: "https://mahatenders.gov.in",
    sourcePortal: SourcePortal.MAHATENDERS,
    status: TenderStatus.CLOSING_SOON,
    scrapedAt: new Date("2025-11-16T06:00:00"),
  },
  {
    title: "Solid Waste Management & Transportation Services for PCMC Area",
    referenceNumber: "PCMC/SWM/2025-26/04",
    description:
      "Door-to-door collection, segregation, transportation, and processing of municipal solid waste for Pimpri-Chinchwad Municipal Corporation area covering 18 zones with an estimated 1,200 MT per day.",
    issuingAuthority: "Pimpri Chinchwad Municipal Corporation",
    department: "Solid Waste Management Department, PCMC",
    category: TenderCategory.OTHER,
    state: "Maharashtra",
    district: "Pune",
    city: "Pimpri-Chinchwad",
    estimatedValue: 2800000000,
    emdAmount: 14000000,
    publishedDate: new Date("2025-11-20"),
    submissionDeadline: new Date("2026-01-05"),
    prebidMeetingDate: new Date("2025-12-10"),
    tenderDocUrl: "https://mahatenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=5710",
    sourceUrl: "https://mahatenders.gov.in",
    sourcePortal: SourcePortal.MAHATENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-11-21T06:00:00"),
  },
  {
    title: "Procurement of Medical Equipment for District Hospitals – Vidarbha Region",
    referenceNumber: "DMER/MH/VID/2025-26/MEQ/07",
    description:
      "Supply and installation of ICU ventilators, C-arm X-ray machines, digital X-ray units, ultrasound machines, and ECG monitors for 12 district hospitals across Amravati and Nagpur divisions.",
    issuingAuthority: "Directorate of Medical Education & Research, Maharashtra",
    department: "Department of Health & Family Welfare, Maharashtra",
    category: TenderCategory.MEDICAL,
    state: "Maharashtra",
    district: "Nagpur",
    city: "Nagpur",
    estimatedValue: 340000000,
    emdAmount: 3400000,
    publishedDate: new Date("2025-12-05"),
    submissionDeadline: new Date("2026-02-10"),
    tenderDocUrl: "https://mahatenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=5801",
    sourceUrl: "https://mahatenders.gov.in",
    sourcePortal: SourcePortal.MAHATENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-06T06:00:00"),
  },

  // ── Tamil Nadu ────────────────────────────────────────────────────────────
  {
    title: "Augmentation of Water Supply Scheme – Chennai Metropolitan Area Phase II",
    referenceNumber: "CMWSSB/WS/2025-26/AUG/11",
    description:
      "Construction of 220 MLD capacity water treatment plant, raw water intake structures, rising mains, and distribution network expansion for Chennai Metropolitan Water Supply and Sewerage Board.",
    issuingAuthority: "Chennai Metropolitan Water Supply & Sewerage Board",
    department: "Municipal Administration & Water Supply Department, TN",
    category: TenderCategory.PLUMBING,
    state: "Tamil Nadu",
    district: "Chennai",
    city: "Chennai",
    estimatedValue: 9200000000,
    emdAmount: 46000000,
    publishedDate: new Date("2025-11-01"),
    submissionDeadline: new Date("2026-01-20"),
    prebidMeetingDate: new Date("2025-11-25"),
    tenderDocUrl: "https://tntenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=3241",
    sourceUrl: "https://tntenders.gov.in",
    sourcePortal: SourcePortal.TNTENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-11-02T06:00:00"),
  },
  {
    title: "Supply of Desktop Computers, Laptops & Peripherals to TN Police Dept",
    referenceNumber: "TNPOL/IT/2025-26/HW/03",
    description:
      "Supply of 5,000 desktop computers (i7 13th gen), 2,000 laptops, 6,000 laser printers, and associated networking equipment for district police offices across Tamil Nadu state.",
    issuingAuthority: "Tamil Nadu Police Department",
    department: "Home Department, Government of Tamil Nadu",
    category: TenderCategory.IT_SERVICES,
    state: "Tamil Nadu",
    district: "Chennai",
    city: "Chennai",
    estimatedValue: 780000000,
    emdAmount: 7800000,
    publishedDate: new Date("2025-12-10"),
    submissionDeadline: new Date("2026-01-25"),
    tenderDocUrl: "https://tntenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=3320",
    sourceUrl: "https://tntenders.gov.in",
    sourcePortal: SourcePortal.TNTENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-11T06:00:00"),
  },
  {
    title: "Electrification of Rural Habitations – Tirunelveli & Thoothukudi Districts",
    referenceNumber: "TANGEDCO/RRE/2025-26/TV/08",
    description:
      "LT & HT line extensions, transformer installations, service connection provisioning and streetlight electrification for 340 unelectrified hamlets in Tirunelveli and Thoothukudi districts under RDSS scheme.",
    issuingAuthority: "Tamil Nadu Generation and Distribution Corporation",
    department: "Energy Department, Government of Tamil Nadu",
    category: TenderCategory.ELECTRICAL,
    state: "Tamil Nadu",
    district: "Tirunelveli",
    city: "Tirunelveli",
    estimatedValue: 1150000000,
    emdAmount: 11500000,
    publishedDate: new Date("2025-11-28"),
    submissionDeadline: new Date("2026-01-10"),
    prebidMeetingDate: new Date("2025-12-12"),
    tenderDocUrl: "https://tntenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=3290",
    sourceUrl: "https://tntenders.gov.in",
    sourcePortal: SourcePortal.TNTENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-11-29T06:00:00"),
  },

  // ── Rajasthan ─────────────────────────────────────────────────────────────
  {
    title: "Construction of Government Model Senior Secondary Schools – Phase III",
    referenceNumber: "RIICO/EDU/2025-26/GMSS/PH3",
    description:
      "Design and construction of 45 government model senior secondary schools in tribal areas of Rajasthan including classrooms, laboratories, libraries, hostels, and sports infrastructure.",
    issuingAuthority: "Rajasthan Integrated Infrastructure Corporation",
    department: "School Education Department, Government of Rajasthan",
    category: TenderCategory.CONSTRUCTION,
    state: "Rajasthan",
    district: "Udaipur",
    city: "Udaipur",
    estimatedValue: 5600000000,
    emdAmount: 28000000,
    publishedDate: new Date("2025-12-08"),
    submissionDeadline: new Date("2026-02-15"),
    prebidMeetingDate: new Date("2025-12-22"),
    tenderDocUrl: "https://eproc.rajasthan.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=6123",
    sourceUrl: "https://eproc.rajasthan.gov.in",
    sourcePortal: SourcePortal.RAJASTHAN_EPROC,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-09T06:00:00"),
  },
  {
    title: "Annual Rate Contract for Supply of Stationery to Government Offices – Jaipur Division",
    referenceNumber: "RAJ/GEN/STAT/2025-26/JD/02",
    description:
      "Rate contract for supply of office stationery items including paper, files, register books, ink cartridges, writing instruments, and envelopes to approx. 380 government offices in Jaipur division for 2 years.",
    issuingAuthority: "Office of the Divisional Commissioner, Jaipur",
    department: "General Administration Department, Rajasthan",
    category: TenderCategory.STATIONERY,
    state: "Rajasthan",
    district: "Jaipur",
    city: "Jaipur",
    estimatedValue: 42000000,
    emdAmount: 420000,
    publishedDate: new Date("2025-11-10"),
    submissionDeadline: new Date("2025-12-28"),
    tenderDocUrl: "https://eproc.rajasthan.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=6050",
    sourceUrl: "https://eproc.rajasthan.gov.in",
    sourcePortal: SourcePortal.RAJASTHAN_EPROC,
    status: TenderStatus.CLOSING_SOON,
    scrapedAt: new Date("2025-11-11T06:00:00"),
  },
  {
    title: "Empanelment of Transport Agencies for Movement of Food Grains – FCI Rajasthan",
    referenceNumber: "FCI/RAJ/TRANS/2025-26/09",
    description:
      "Empanelment of road transport contractors for movement of wheat, rice, and other food grains between FCI depots, procurement centres, and fair price shops across all 33 districts of Rajasthan.",
    issuingAuthority: "Food Corporation of India – Rajasthan Region",
    department: "FCI Regional Office, Jaipur",
    category: TenderCategory.TRANSPORTATION,
    state: "Rajasthan",
    district: "Jaipur",
    city: "Jaipur",
    estimatedValue: 1800000000,
    emdAmount: 9000000,
    publishedDate: new Date("2025-12-03"),
    submissionDeadline: new Date("2026-01-30"),
    prebidMeetingDate: new Date("2025-12-18"),
    tenderDocUrl: "https://eproc.rajasthan.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=6098",
    sourceUrl: "https://eproc.rajasthan.gov.in",
    sourcePortal: SourcePortal.RAJASTHAN_EPROC,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-04T06:00:00"),
  },

  // ── Central / CPPP ────────────────────────────────────────────────────────
  {
    title: "Procurement of Servers, Storage & Networking Equipment for NIC Data Centre",
    referenceNumber: "NIC/INFRA/2025-26/HW/15",
    description:
      "Procurement of rack servers (2U form factor), SAN storage arrays, core and access layer network switches, firewalls, and load balancers for NIC National Data Centre expansion project in Delhi.",
    issuingAuthority: "National Informatics Centre",
    department: "Ministry of Electronics & Information Technology",
    category: TenderCategory.IT_SERVICES,
    state: "Delhi",
    district: "New Delhi",
    city: "New Delhi",
    estimatedValue: 2400000000,
    emdAmount: 24000000,
    publishedDate: new Date("2025-11-25"),
    submissionDeadline: new Date("2026-01-08"),
    prebidMeetingDate: new Date("2025-12-10"),
    tenderDocUrl: "https://eprocure.gov.in/eprocure/app?page=FrontEndTenderDetail&service=page&sd=3&pid=7845",
    sourceUrl: "https://eprocure.gov.in",
    sourcePortal: SourcePortal.CPPP,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-11-26T06:00:00"),
  },
  {
    title: "Consultancy Services for Preparation of City Master Plan 2041 – DUSIB",
    referenceNumber: "DUSIB/PLG/2025-26/CMP/01",
    description:
      "Appointment of consultancy firm for preparation of comprehensive city master plan 2041 including land use planning, transport network planning, green zone demarcation, and smart city integration for Delhi.",
    issuingAuthority: "Delhi Urban Shelter Improvement Board",
    department: "Urban Development Department, Government of NCT Delhi",
    category: TenderCategory.CONSULTING,
    state: "Delhi",
    district: "New Delhi",
    city: "New Delhi",
    estimatedValue: 85000000,
    emdAmount: 850000,
    publishedDate: new Date("2025-12-12"),
    submissionDeadline: new Date("2026-02-20"),
    prebidMeetingDate: new Date("2026-01-05"),
    tenderDocUrl: "https://eprocure.gov.in/eprocure/app?page=FrontEndTenderDetail&service=page&sd=3&pid=7901",
    sourceUrl: "https://eprocure.gov.in",
    sourcePortal: SourcePortal.CPPP,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-13T06:00:00"),
  },
  {
    title: "Supply of Essential Medicines & Surgical Consumables – CGHS Delhi Dispensaries",
    referenceNumber: "CGHS/DEL/MED/2025-26/RC/18",
    description:
      "Rate contract for supply of scheduled essential medicines, surgical dressings, sutures, IV fluids, and diagnostic reagents to 72 CGHS wellness centres and dispensaries in Delhi NCR region.",
    issuingAuthority: "Central Government Health Scheme, Delhi",
    department: "Ministry of Health & Family Welfare",
    category: TenderCategory.MEDICAL,
    state: "Delhi",
    district: "New Delhi",
    city: "New Delhi",
    estimatedValue: 560000000,
    emdAmount: 5600000,
    publishedDate: new Date("2025-11-18"),
    submissionDeadline: new Date("2025-12-31"),
    tenderDocUrl: "https://eprocure.gov.in/eprocure/app?page=FrontEndTenderDetail&service=page&sd=3&pid=7798",
    sourceUrl: "https://eprocure.gov.in",
    sourcePortal: SourcePortal.CPPP,
    status: TenderStatus.CLOSING_SOON,
    scrapedAt: new Date("2025-11-19T06:00:00"),
  },

  // ── Indian Railways / IREPS ───────────────────────────────────────────────
  {
    title: "Construction of ROB (Road Over Bridge) at Level Crossing No. 54 – CR Division",
    referenceNumber: "CR/PUNE/CIVIL/2025-26/ROB/54",
    description:
      "Construction of road over bridge at level crossing 54 near Talegaon station on Pune–Mumbai main line including pile foundation, PSC girders, approach roads, and traffic diversions during construction.",
    issuingAuthority: "Central Railway – Pune Division",
    department: "Indian Railways, Ministry of Railways",
    category: TenderCategory.CONSTRUCTION,
    state: "Maharashtra",
    district: "Pune",
    city: "Talegaon Dabhade",
    estimatedValue: 1420000000,
    emdAmount: 14200000,
    publishedDate: new Date("2025-12-01"),
    submissionDeadline: new Date("2026-01-20"),
    prebidMeetingDate: new Date("2025-12-15"),
    tenderDocUrl: "https://www.ireps.gov.in/ireps/tenderDetails.do?tenderId=897654",
    sourceUrl: "https://www.ireps.gov.in",
    sourcePortal: SourcePortal.IREPS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-02T06:00:00"),
  },
  {
    title: "Annual Maintenance Contract for Electrical Installations – Western Railway HQ",
    referenceNumber: "WR/ELEC/AMC/2025-26/HQ/07",
    description:
      "AMC for maintenance of electrical installations including substations, OHE, DG sets, UPS systems, interior lighting, and escalators at Western Railway headquarters complex at Churchgate, Mumbai.",
    issuingAuthority: "Western Railway – Headquarters",
    department: "Electrical Department, Western Railway",
    category: TenderCategory.ELECTRICAL,
    state: "Maharashtra",
    district: "Mumbai",
    city: "Mumbai",
    estimatedValue: 145000000,
    emdAmount: 1450000,
    publishedDate: new Date("2025-11-22"),
    submissionDeadline: new Date("2025-12-29"),
    tenderDocUrl: "https://www.ireps.gov.in/ireps/tenderDetails.do?tenderId=891234",
    sourceUrl: "https://www.ireps.gov.in",
    sourcePortal: SourcePortal.IREPS,
    status: TenderStatus.CLOSING_SOON,
    scrapedAt: new Date("2025-11-23T06:00:00"),
  },

  // ── Government e-Marketplace (GeM) ───────────────────────────────────────
  {
    title: "Procurement of Electric Buses for BEST Mumbai Fleet Augmentation",
    referenceNumber: "BEST/TRANS/EV/2025-26/BUS/200",
    description:
      "Procurement of 200 twelve-metre electric buses with charging infrastructure, depot equipment, and 10-year comprehensive maintenance contract for Brihanmumbai Electric Supply and Transport undertaking.",
    issuingAuthority: "Brihanmumbai Electric Supply & Transport",
    department: "Urban Transport Department, BMC",
    category: TenderCategory.TRANSPORTATION,
    state: "Maharashtra",
    district: "Mumbai",
    city: "Mumbai",
    estimatedValue: 7600000000,
    emdAmount: 38000000,
    publishedDate: new Date("2025-12-07"),
    submissionDeadline: new Date("2026-02-28"),
    prebidMeetingDate: new Date("2025-12-28"),
    tenderDocUrl: "https://bidplus.gem.gov.in/all-bids/bid-detail/GEM/2025/B/5432109",
    sourceUrl: "https://gem.gov.in",
    sourcePortal: SourcePortal.GEM,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-08T06:00:00"),
  },
  {
    title: "Rate Contract for Plumbing & Sanitation Maintenance Works – CPWD Zone 5 Delhi",
    referenceNumber: "CPWD/Z5/PLB/RC/2025-26/03",
    description:
      "Rate contract for plumbing maintenance including pipe repairs, sanitation fittings replacement, water pump servicing, sewage treatment plant upkeep at 210 central government office buildings in CPWD Zone 5.",
    issuingAuthority: "Central Public Works Department – Zone 5",
    department: "Ministry of Housing & Urban Affairs",
    category: TenderCategory.PLUMBING,
    state: "Delhi",
    district: "New Delhi",
    city: "New Delhi",
    estimatedValue: 95000000,
    emdAmount: 950000,
    publishedDate: new Date("2025-11-05"),
    submissionDeadline: new Date("2025-12-20"),
    tenderDocUrl: "https://bidplus.gem.gov.in/all-bids/bid-detail/GEM/2025/B/5401234",
    sourceUrl: "https://gem.gov.in",
    sourcePortal: SourcePortal.GEM,
    status: TenderStatus.CLOSED,
    scrapedAt: new Date("2025-11-06T06:00:00"),
  },
  {
    title: "Empanelment of IT Consulting Firms for Digital Transformation – SIDBI",
    referenceNumber: "SIDBI/IT/CONSULT/2025-26/04",
    description:
      "Empanelment of IT consulting and system integration companies for digital transformation projects including core banking modernisation, mobile banking platform development, and AI-based credit scoring for SIDBI.",
    issuingAuthority: "Small Industries Development Bank of India",
    department: "SIDBI – IT & Digital Transformation Division",
    category: TenderCategory.CONSULTING,
    state: "Uttar Pradesh",
    district: "Lucknow",
    city: "Lucknow",
    estimatedValue: 320000000,
    emdAmount: 3200000,
    publishedDate: new Date("2025-12-14"),
    submissionDeadline: new Date("2026-02-05"),
    prebidMeetingDate: new Date("2026-01-08"),
    tenderDocUrl: "https://eprocure.gov.in/eprocure/app?page=FrontEndTenderDetail&service=page&sd=3&pid=7955",
    sourceUrl: "https://eprocure.gov.in",
    sourcePortal: SourcePortal.CPPP,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-15T06:00:00"),
  },
  {
    title: "Construction of Integrated Bus Terminal cum Commercial Complex – Coimbatore",
    referenceNumber: "TNSTC/INFRA/CBE/2025-26/IBT/01",
    description:
      "Design, build, and operate integrated bus terminal with shopping complex, food court, parking for 500 vehicles, and last-mile connectivity infrastructure at Gandhipuram, Coimbatore on PPP model.",
    issuingAuthority: "Tamil Nadu State Transport Corporation – Coimbatore",
    department: "Transport Department, Government of Tamil Nadu",
    category: TenderCategory.CONSTRUCTION,
    state: "Tamil Nadu",
    district: "Coimbatore",
    city: "Coimbatore",
    estimatedValue: 3200000000,
    emdAmount: 16000000,
    publishedDate: new Date("2025-11-30"),
    submissionDeadline: new Date("2026-02-01"),
    prebidMeetingDate: new Date("2025-12-20"),
    tenderDocUrl: "https://tntenders.gov.in/nicgep/app?page=FrontEndTenderDetail&service=page&sd=3&pid=3388",
    sourceUrl: "https://tntenders.gov.in",
    sourcePortal: SourcePortal.TNTENDERS,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-01T06:00:00"),
  },
  {
    title: "Annual Supply of Laboratory Consumables & Reagents – IIT Jodhpur",
    referenceNumber: "IITJ/ACAD/LAB/RC/2025-26/11",
    description:
      "Rate contract for annual supply of laboratory chemicals, glassware, reagent kits, PCR consumables, and analytical instruments accessories for research laboratories of IIT Jodhpur.",
    issuingAuthority: "Indian Institute of Technology Jodhpur",
    department: "Research & Development Cell, IIT Jodhpur",
    category: TenderCategory.OTHER,
    state: "Rajasthan",
    district: "Jodhpur",
    city: "Jodhpur",
    estimatedValue: 28000000,
    emdAmount: 280000,
    publishedDate: new Date("2025-12-10"),
    submissionDeadline: new Date("2026-01-15"),
    tenderDocUrl: "https://eprocure.gov.in/eprocure/app?page=FrontEndTenderDetail&service=page&sd=3&pid=7963",
    sourceUrl: "https://eprocure.gov.in",
    sourcePortal: SourcePortal.CPPP,
    status: TenderStatus.OPEN,
    scrapedAt: new Date("2025-12-11T06:00:00"),
  },
];

async function main() {
  console.log("🌱  Seeding database...\n");

  // Clear existing seed data (dev only)
  await prisma.scraperLog.deleteMany();
  await prisma.bookmark.deleteMany();
  await prisma.alert.deleteMany();
  await prisma.user.deleteMany();
  await prisma.tender.deleteMany();

  // Insert tenders
  let created = 0;
  for (const tender of tenders) {
    await prisma.tender.create({ data: tender as any });
    created++;
    process.stdout.write(`\r  Inserted ${created}/${tenders.length} tenders`);
  }
  console.log("\n");

  // Sample scraper logs
  await prisma.scraperLog.createMany({
    data: [
      {
        sourcePortal: SourcePortal.MAHATENDERS,
        status: "SUCCESS",
        tendersFound: 128,
        tendersNew: 14,
        tendersUpdated: 6,
        startedAt: new Date("2025-12-15T02:00:00"),
        completedAt: new Date("2025-12-15T02:04:32"),
        duration: 272,
      },
      {
        sourcePortal: SourcePortal.TNTENDERS,
        status: "SUCCESS",
        tendersFound: 94,
        tendersNew: 8,
        tendersUpdated: 3,
        startedAt: new Date("2025-12-15T02:05:00"),
        completedAt: new Date("2025-12-15T02:08:11"),
        duration: 191,
      },
      {
        sourcePortal: SourcePortal.CPPP,
        status: "PARTIAL",
        tendersFound: 203,
        tendersNew: 19,
        tendersUpdated: 11,
        errorMessage: "Pagination failed at page 9 – rate limited by source portal",
        startedAt: new Date("2025-12-15T02:10:00"),
        completedAt: new Date("2025-12-15T02:17:45"),
        duration: 465,
      },
      {
        sourcePortal: SourcePortal.GEM,
        status: "SUCCESS",
        tendersFound: 312,
        tendersNew: 28,
        tendersUpdated: 17,
        startedAt: new Date("2025-12-15T02:20:00"),
        completedAt: new Date("2025-12-15T02:27:59"),
        duration: 479,
      },
    ],
  });

  // Sample user
  const user = await prisma.user.create({
    data: {
      name: "Ramesh Tiwari",
      email: "ramesh.tiwari@constructionsolutions.in",
      phone: "+919876543210",
      password: "$2b$10$K7L1OJ45/4Y2nIvhRVpCe.FIlmBNY7VkJg7VnP9lOt2oF.Ds.mLhW", // bcrypt hash placeholder
      companyName: "Tiwari Construction Solutions Pvt Ltd",
      udyamNumber: "UDYAM-MH-12-0034521",
      gstNumber: "27AABCT1234F1ZP",
      turnover: 250000000,
      state: "Maharashtra",
      district: "Pune",
      preferredCategories: ["CONSTRUCTION", "ELECTRICAL", "PLUMBING"],
      preferredStates: ["Maharashtra", "Goa", "Karnataka"],
      isVerified: true,
    },
  });

  // Sample alert for the user
  await prisma.alert.create({
    data: {
      userId: user.id,
      name: "Maharashtra Construction Tenders",
      categories: ["CONSTRUCTION", "ELECTRICAL"],
      states: ["Maharashtra"],
      minValue: 10000000,
      keywords: ["PWD", "road", "bridge", "highway"],
      isActive: true,
      channel: "EMAIL",
      frequency: "DAILY_DIGEST",
    },
  });

  console.log("✅  Seed complete:");
  console.log(`   • ${tenders.length} tenders`);
  console.log(`   • 4 scraper logs`);
  console.log(`   • 1 sample user (ramesh.tiwari@constructionsolutions.in)`);
  console.log(`   • 1 alert\n`);
}

main()
  .catch((e) => {
    console.error("❌  Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
